spring.application.name=security

server.port = 8090

spring.datasource.url = jdbc:mysql://localhost:3306/mysecurity?createDatabaseIfNotExist=true
spring.datasource.username = root
spring.datasource.password = manager

spring.jpa.hibernate.ddl-auto = update

spring.cache.type = simple

jwt.token.secret= spring-boot-starter-validation-test
jwt.token.expiry.millis = 3600000